INSERT INTO grade (name, description)
VALUES ('1-K', '1ro de kinder');
INSERT INTO grade (name, description)
VALUES ('2-K', '2do de kinder');
INSERT INTO grade (name, description)
VALUES ('3-K', '3ro de kinder');
INSERT INTO grade (name, description)
VALUES ('1-P', '1ro de primaria');
INSERT INTO grade (name, description)
VALUES ('2-P', '2do de primaria');
INSERT INTO grade (name, description)
VALUES ('3-P', '3ro de primaria');
INSERT INTO grade (name, description)
VALUES ('4-P', '4to de primaria');
INSERT INTO grade (name, description)
VALUES ('5-P', '5to de primaria');
INSERT INTO grade (name, description)
VALUES ('6-P', '6to de primaria');
COMMIT;